[package]
name = "srad-eon"
version = "0.1.0"
edition = "2021"

[dependencies]
srad-types = { path = "../srad-types" }
srad-client = { path = "../srad-client" }
tokio = { workspace = true }
futures = { workspace = true }
flume = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }