[package]
name = "srad"
version = "0.1.0"
edition = "2021"

[dependencies]
srad-eon = { path = "../srad-eon" }
srad-app = { path = "../srad-app" }
srad-client = { path = "../srad-client" }
srad-client-rumqtt = { path = "../srad-client-rumqtt" }
srad-types = { path = "../srad-types" }
