[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
srad = { version = "0.1.0", path = "../srad" }
log = { workspace = true }
tokio = { workspace = true }
env_logger = "0.11.7"

[[example]]
name = "simple-app"
path = "app/simple.rs"

[[example]]
name = "simple-node"
path = "eon/simple.rs"
